// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dict.proto

#ifndef PROTOBUF_dict_2eproto__INCLUDED
#define PROTOBUF_dict_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace protobuf {
class Dict;
class DictDefaultTypeInternal;
extern DictDefaultTypeInternal _Dict_default_instance_;
class Dict_Featureid2sortidEntry;
class Dict_Featureid2sortidEntryDefaultTypeInternal;
extern Dict_Featureid2sortidEntryDefaultTypeInternal _Dict_Featureid2sortidEntry_default_instance_;
class Dict_Field2feanumEntry;
class Dict_Field2feanumEntryDefaultTypeInternal;
extern Dict_Field2feanumEntryDefaultTypeInternal _Dict_Field2feanumEntry_default_instance_;
class Dict_Field2missidEntry;
class Dict_Field2missidEntryDefaultTypeInternal;
extern Dict_Field2missidEntryDefaultTypeInternal _Dict_Field2missidEntry_default_instance_;
}  // namespace protobuf

namespace protobuf {

namespace protobuf_dict_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_dict_2eproto

// ===================================================================


// -------------------------------------------------------------------


// -------------------------------------------------------------------


// -------------------------------------------------------------------

class Dict : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobuf.Dict) */ {
 public:
  Dict();
  virtual ~Dict();

  Dict(const Dict& from);

  inline Dict& operator=(const Dict& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Dict(Dict&& from) noexcept
    : Dict() {
    *this = ::std::move(from);
  }

  inline Dict& operator=(Dict&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Dict& default_instance();

  static inline const Dict* internal_default_instance() {
    return reinterpret_cast<const Dict*>(
               &_Dict_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Dict* other);
  friend void swap(Dict& a, Dict& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Dict* New() const PROTOBUF_FINAL { return New(NULL); }

  Dict* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Dict& from);
  void MergeFrom(const Dict& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Dict* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint64, uint64> featureid2sortid = 1;
  int featureid2sortid_size() const;
  void clear_featureid2sortid();
  static const int kFeatureid2SortidFieldNumber = 1;
  const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
      featureid2sortid() const;
  ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
      mutable_featureid2sortid();

  // map<uint32, uint64> field2missid = 2;
  int field2missid_size() const;
  void clear_field2missid();
  static const int kField2MissidFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >&
      field2missid() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >*
      mutable_field2missid();

  // map<uint32, uint64> field2feanum = 3;
  int field2feanum_size() const;
  void clear_field2feanum();
  static const int kField2FeanumFieldNumber = 3;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >&
      field2feanum() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >*
      mutable_field2feanum();

  // @@protoc_insertion_point(class_scope:protobuf.Dict)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  public:
  class Dict_Featureid2sortidEntry : public ::google::protobuf::internal::MapEntry<Dict_Featureid2sortidEntry, 
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<Dict_Featureid2sortidEntry, 
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > SuperType;
    Dict_Featureid2sortidEntry();
    Dict_Featureid2sortidEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const Dict_Featureid2sortidEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_Dict_Featureid2sortidEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      Dict_Featureid2sortidEntry,
      ::google::protobuf::uint64, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > featureid2sortid_;
  private:
  public:
  class Dict_Field2missidEntry : public ::google::protobuf::internal::MapEntry<Dict_Field2missidEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<Dict_Field2missidEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > SuperType;
    Dict_Field2missidEntry();
    Dict_Field2missidEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const Dict_Field2missidEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_Dict_Field2missidEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      Dict_Field2missidEntry,
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > field2missid_;
  private:
  public:
  class Dict_Field2feanumEntry : public ::google::protobuf::internal::MapEntry<Dict_Field2feanumEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<Dict_Field2feanumEntry, 
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > SuperType;
    Dict_Field2feanumEntry();
    Dict_Field2feanumEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const Dict_Field2feanumEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_Dict_Field2feanumEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      Dict_Field2feanumEntry,
      ::google::protobuf::uint32, ::google::protobuf::uint64,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT64,
      0 > field2feanum_;
  private:
  friend struct protobuf_dict_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Dict

// map<uint64, uint64> featureid2sortid = 1;
inline int Dict::featureid2sortid_size() const {
  return featureid2sortid_.size();
}
inline void Dict::clear_featureid2sortid() {
  featureid2sortid_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >&
Dict::featureid2sortid() const {
  // @@protoc_insertion_point(field_map:protobuf.Dict.featureid2sortid)
  return featureid2sortid_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint64, ::google::protobuf::uint64 >*
Dict::mutable_featureid2sortid() {
  // @@protoc_insertion_point(field_mutable_map:protobuf.Dict.featureid2sortid)
  return featureid2sortid_.MutableMap();
}

// map<uint32, uint64> field2missid = 2;
inline int Dict::field2missid_size() const {
  return field2missid_.size();
}
inline void Dict::clear_field2missid() {
  field2missid_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >&
Dict::field2missid() const {
  // @@protoc_insertion_point(field_map:protobuf.Dict.field2missid)
  return field2missid_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >*
Dict::mutable_field2missid() {
  // @@protoc_insertion_point(field_mutable_map:protobuf.Dict.field2missid)
  return field2missid_.MutableMap();
}

// map<uint32, uint64> field2feanum = 3;
inline int Dict::field2feanum_size() const {
  return field2feanum_.size();
}
inline void Dict::clear_field2feanum() {
  field2feanum_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >&
Dict::field2feanum() const {
  // @@protoc_insertion_point(field_map:protobuf.Dict.field2feanum)
  return field2feanum_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint64 >*
Dict::mutable_field2feanum() {
  // @@protoc_insertion_point(field_mutable_map:protobuf.Dict.field2feanum)
  return field2feanum_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dict_2eproto__INCLUDED
